<?php

namespace App\Services;

use DOMDocument;
use DOMElement;
use DOMNode;

class RichTextSanitizer
{
    /**
     * Sanitize HTML generated by Quill.
     *
     * Allowed tags:
     * p, br, strong, b, em, i, u, s,
     * h2, h3, blockquote, ol, ul, li, a
     *
     * Allowed attributes:
     * - a: href
     * - li: data-list (Quill)
     */
    public function sanitize(string $html): string
    {
        if (trim($html) === '') {
            return '';
        }

        $allowedTags = [
            'p',
            'br',
            'strong',
            'b',
            'em',
            'i',
            'u',
            's',
            'h2',
            'h3',
            'blockquote',
            'ol',
            'ul',
            'li',
            'a',
        ];

        libxml_use_internal_errors(true);

        $dom = new DOMDocument('1.0', 'UTF-8');

        $html = '<?xml encoding="UTF-8">'
            . '<div id="rich-text-root">'
            . $html
            . '</div>';

        $dom->loadHTML(
            $html,
            LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD
        );

        libxml_clear_errors();

        $root = $dom->getElementById('rich-text-root');

        if (! $root) {
            return '';
        }

        $this->sanitizeChildren($root, $allowedTags);

        $result = '';

        foreach ($root->childNodes as $child) {
            $result .= $dom->saveHTML($child);
        }

        return trim($result);
    }

    private function sanitizeChildren(
        DOMNode $parent,
        array $allowedTags
    ): void {
        /*
         * Copy the children first because the DOM tree
         * may be modified while we process it.
         */
        $children = [];

        foreach ($parent->childNodes as $child) {
            $children[] = $child;
        }

        foreach ($children as $node) {
            if ($node->nodeType === XML_COMMENT_NODE) {
                $parent->removeChild($node);
                continue;
            }

            /*
             * Text nodes are safe.
             */
            if ($node->nodeType === XML_TEXT_NODE) {
                continue;
            }

            /*
             * Ignore anything that is not an element.
             */
            if (! $node instanceof DOMElement) {
                continue;
            }

            $tag = strtolower($node->tagName);

            /*
             * Dangerous elements are completely removed,
             * including their contents.
             */
            if (in_array($tag, [
                'script',
                'style',
                'iframe',
                'object',
                'embed',
                'form',
                'input',
                'button',
                'textarea',
                'select',
                'option',
                'svg',
                'math',
            ], true)) {
                $parent->removeChild($node);
                continue;
            }

            /*
             * Unsupported elements are removed,
             * but their text/children are preserved.
             *
             * Example:
             * <span>Hello</span>
             *
             * becomes:
             * Hello
             */
            if (! in_array($tag, $allowedTags, true)) {
                while ($node->firstChild) {
                    $parent->insertBefore($node->firstChild, $node);
                }

                $parent->removeChild($node);
                continue;
            }

            /*
             * Save attributes we actually need before
             * removing everything else.
             */
            $href = null;
            $dataList = null;

            if ($tag === 'a' && $node->hasAttribute('href')) {
                $href = trim($node->getAttribute('href'));
            }

            if ($tag === 'li' && $node->hasAttribute('data-list')) {
                $dataList = trim($node->getAttribute('data-list'));
            }

            /*
             * Remove ALL attributes.
             *
             * This removes:
             * onclick
             * onerror
             * style
             * class
             * id
             * etc.
             */
            while ($node->attributes->length > 0) {
                $node->removeAttribute(
                    $node->attributes->item(0)->name
                );
            }

            /*
             * Restore href only when the URL is safe.
             */
            if ($tag === 'a' && $href !== null && $this->isSafeHref($href)) {
                $node->setAttribute('href', $href);
            }

            /*
             * Quill 2 uses data-list to distinguish
             * bullet and ordered lists.
             */
            if (
                $tag === 'li'
                && in_array($dataList, ['bullet', 'ordered'], true)
            ) {
                $node->setAttribute('data-list', $dataList);
            }

            /*
             * Continue sanitizing nested elements.
             */
            $this->sanitizeChildren($node, $allowedTags);
        }
    }

    private function isSafeHref(string $href): bool
    {
        /*
         * Allow:
         *
         * https://example.com
         * http://example.com
         * /internal-page
         * /profile/user
         * #section
         * ?query=value
         */
        if (preg_match('#^https?://#i', $href)) {
            return true;
        }

        if (str_starts_with($href, '/')) {
            /*
             * Reject protocol-relative URLs:
             * //evil.example.com
             */
            return ! str_starts_with($href, '//');
        }

        if (str_starts_with($href, '#')) {
            return true;
        }

        if (str_starts_with($href, '?')) {
            return true;
        }

        return false;
    }
}

